#: kivy 1.11.1
#: include screens/starting.kv
#: include screens/home.kv
#: include screens/basic.kv
#: include screens/advanced.kv


FloatLayout:

    ScreenManager:
        id: screen_manager
        Starting:
            name: "starting_page"
            id: start
        Home:
            name: "home_page"
            id: home
        Basic:
            name: "basic_calculator"
            id: basic
        Advanced:
            name: "advanced_calculator"
            id: advanced

 